AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    aws-sam-express

    SAM Template

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

    SocialEventsFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: ./
            Handler: lambda.handler
            Runtime: nodejs8.10
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                SocialEventsAPIRoot:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /
                        Method: ANY
                SocialEventsAPI:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /{proxy+}
                        Method: ANY

Outputs:

    SocialEventsAPI:
        Description: "API Gateway endpoint URL for Prod stage"
        Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"

    SocialEventsFunction:
        Description: "Social Events Lambda Function ARN"
        Value: !GetAtt SocialEventsFunction.Arn

    SocialEventsFunctionIamRole:
        Description: "Implicit IAM Role created for Social Events function"
        Value: !GetAtt SocialEventsFunction.Arn
